# Generated by Django 3.1.2 on 2021-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_found',
            field=models.DateTimeField(),
        ),
    ]
