# Generated by Django 3.1.2 on 2021-03-13 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0002_auto_20210313_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_found',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 34, 423846)),
        ),
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 3, 13, 9, 48, 34, 423846, tzinfo=utc)),
        ),
    ]
