# Generated by Django 3.1.2 on 2021-03-13 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0003_auto_20210313_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 45, 27, 646133)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 3, 13, 10, 15, 27, 646133, tzinfo=utc)),
        ),
    ]
