# Generated by Django 3.1.2 on 2021-03-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0004_auto_20210313_1542'),
        ('found', '0005_auto_20210313_1552'),
    ]

    operations = [
    ]
