# Generated by Django 3.1.2 on 2021-03-13 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0006_merge_20210313_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 13, 18, 59, 10, 120288)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 3, 13, 13, 29, 10, 120288, tzinfo=utc)),
        ),
    ]
