# Generated by Django 3.1.2 on 2021-03-13 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0009_auto_20210313_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 13, 19, 17, 22, 928295)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 3, 13, 13, 47, 22, 928295, tzinfo=utc)),
        ),
    ]
