# Generated by Django 3.1.7 on 2021-03-13 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0010_auto_20210313_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location_found',
        ),
        migrations.AddField(
            model_name='product',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 14, 0, 40, 1, 681948)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 3, 13, 19, 10, 1, 681948, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
