# Generated by Django 3.1.2 on 2021-03-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0011_auto_20210314_0040'),
        ('found', '0011_auto_20210313_2246'),
    ]

    operations = [
    ]
