# Generated by Django 3.1.7 on 2021-03-13 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('found', '0014_auto_20210314_0510'),
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('isLost', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='found.product')),
            ],
        ),
    ]
