# Generated by Django 3.1.2 on 2021-03-13 22:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('tags', models.CharField(max_length=200)),
                ('time', models.TimeField(blank=True, default=datetime.datetime(2021, 3, 13, 22, 20, 23, 347987, tzinfo=utc))),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 3, 14, 3, 50, 23, 347987))),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('isLost', models.BooleanField(default=False)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
