# Generated by Django 3.1.7 on 2021-03-13 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_auto_20210314_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 14, 5, 20, 27, 666921)),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 3, 13, 23, 50, 27, 666921, tzinfo=utc)),
        ),
    ]
